apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: darkelfio-com-tls
spec:
  secretName: darkelfio-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: darkelfio.com
  dnsNames:
    - darkelfio.com
    - www.darkelfio.com
  acme:
    config:
      - http01:
         ingressClass: nginx
        domains:
          - darkelfio.com
          - www.darkelfio.com 
